name: polymath_ai
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit=11.8  # Adjust based on your CUDA version
  - librosa
  - opencv
  - pip:
    - transformers>=4.30.0
    - tokenizers>=0.13.3
    - torch-geometric>=2.3.0
    - pgmpy>=0.2.10
    - SpeechRecognition>=3.8.1
    - neo4j>=5.10.0
    - rdflib>=6.3.2
    - stable-baselines3>=2.0.0
